# Numerical Analysis Assignment #6

2018112749 전현승


In [1]:
import numpy as np

In [2]:
A = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])
b = np.array([[7.85, -19.3, 71.4]])
print(A.shape)
print(b.shape)

(3, 3)
(1, 3)


In [3]:
M = np.append(A, np.reshape(b, (-1, 1)), axis=1)
M

array([[  3.  ,  -0.1 ,  -0.2 ,   7.85],
       [  0.1 ,   7.  ,  -0.3 , -19.3 ],
       [  0.3 ,  -0.2 ,  10.  ,  71.4 ]])

In [4]:
R, C = M.shape

In [5]:
for row in range(R):
  for row_down in range(row + 1, R):
    M[row_down] -= M[row] * (M[row_down][row] / M[row][row])
    print(M)
    print()

[[  3.          -0.1         -0.2          7.85      ]
 [  0.           7.00333333  -0.29333333 -19.56166667]
 [  0.3         -0.2         10.          71.4       ]]

[[  3.          -0.1         -0.2          7.85      ]
 [  0.           7.00333333  -0.29333333 -19.56166667]
 [  0.          -0.19        10.02        70.615     ]]

[[  3.          -0.1         -0.2          7.85      ]
 [  0.           7.00333333  -0.29333333 -19.56166667]
 [  0.           0.          10.01204188  70.08429319]]



In [6]:
x = [0 for _ in range(R)]
x[R - 1] = M[R - 1][C - 1] / M[R - 1][R - 1]
print(x)

[0, 0, 7.000000000000002]


In [7]:
for i in range(R - 2, -1, -1):
  s = 0
  for j in range(i + 1, R):
    s += x[j] * M[i][j]
  x[i] = (M[i][C - 1] - s) / M[i][i]

print(x)

[3.0, -2.5, 7.000000000000002]


In [8]:
for i in range(len(x)):
  print(f"x_{i}: {x[i]}")

x_0: 3.0
x_1: -2.5
x_2: 7.000000000000002
