# Numerical Analysis Assignment #7

2018112749 전현승


In [1]:
import numpy as np

## Q1. Gauss elimination with partial pivoting

## Q1. (a)

In [2]:
A = np.array([[6, 4, 13], [2, 1, -1], [-3, 6, -1]]).astype("float64")
b = np.array([[-23, 4, 8]]).astype("float64")
print(A.shape)
print(b.shape)

(3, 3)
(1, 3)


In [3]:
M = np.append(A, np.reshape(b, (-1, 1)), axis=1)
M

array([[  6.,   4.,  13., -23.],
       [  2.,   1.,  -1.,   4.],
       [ -3.,   6.,  -1.,   8.]])

In [4]:
R, C = M.shape

In [5]:
for row in range(R):
    ## partial pivoting: sort rows [row:R] by row-th column
    # split M to upper/lower (horizontal)
    upper = M[0:row]
    lower = M[row:]

    # sort lower
    col = lower[:, row]
    idx = np.argsort(-col)  # descending
    lower = lower[idx]

    # concatenate
    M = np.append(upper, lower, axis=0)

    for row_down in range(row + 1, R):
        M[row_down] -= M[row] * (M[row_down][row] / M[row][row])
        print(M)
        print()

[[  6.           4.          13.         -23.        ]
 [  0.          -0.33333333  -5.33333333  11.66666667]
 [ -3.           6.          -1.           8.        ]]

[[  6.           4.          13.         -23.        ]
 [  0.          -0.33333333  -5.33333333  11.66666667]
 [  0.           8.           5.5         -3.5       ]]

[[  6.           4.          13.         -23.        ]
 [  0.           8.           5.5         -3.5       ]
 [  0.           0.          -5.10416667  11.52083333]]



In [6]:
x = [0 for _ in range(R)]
x[R - 1] = M[R - 1][C - 1] / M[R - 1][R - 1]
print(x)

[0, 0, -2.257142857142857]


In [7]:
for i in range(R - 2, -1, -1):
    s = 0
    for j in range(i + 1, R):
        s += x[j] * M[i][j]
    x[i] = (M[i][C - 1] - s) / M[i][i]

print(x)

[0.31428571428571433, 1.1142857142857143, -2.257142857142857]


In [8]:
for i in range(len(x)):
    print(f"x_{i}: {x[i]}")

x_0: 0.31428571428571433
x_1: 1.1142857142857143
x_2: -2.257142857142857


## Q1. (b)

In [9]:
A = np.array([[-2, -3, 1, 2], [7, 6, 0, -3], [0, 3, 1, 5], [2, -2, 6, 6]]).astype("float64")
b = np.array([[2, -4, 1, 8]]).astype("float64")
print(A.shape)
print(b.shape)

(4, 4)
(1, 4)


In [10]:
M = np.append(A, np.reshape(b, (-1, 1)), axis=1)
R, C = M.shape

for row in range(R):
    ## partial pivoting: sort rows [row:R] by row-th column
    # split M to upper/lower (horizontal)
    upper = M[0:row]
    lower = M[row:]

    # sort lower
    col = lower[:, row]
    idx = np.argsort(-col)  # descending
    lower = lower[idx]

    # concatenate
    M = np.append(upper, lower, axis=0)

    for row_down in range(row + 1, R):
        M[row_down] -= M[row] * (M[row_down][row] / M[row][row])
        print(M)
        print()

[[ 7.          6.          0.         -3.         -4.        ]
 [ 0.         -3.71428571  6.          6.85714286  9.14285714]
 [ 0.          3.          1.          5.          1.        ]
 [-2.         -3.          1.          2.          2.        ]]

[[ 7.          6.          0.         -3.         -4.        ]
 [ 0.         -3.71428571  6.          6.85714286  9.14285714]
 [ 0.          3.          1.          5.          1.        ]
 [-2.         -3.          1.          2.          2.        ]]

[[ 7.          6.          0.         -3.         -4.        ]
 [ 0.         -3.71428571  6.          6.85714286  9.14285714]
 [ 0.          3.          1.          5.          1.        ]
 [ 0.         -1.28571429  1.          1.14285714  0.85714286]]

[[ 7.          6.          0.         -3.         -4.        ]
 [ 0.          3.          1.          5.          1.        ]
 [ 0.          0.          1.42857143  3.28571429  1.28571429]
 [ 0.         -3.71428571  6.          6.85714286

In [11]:
x = [0 for _ in range(R)]
x[R - 1] = M[R - 1][C - 1] / M[R - 1][R - 1]

for i in range(R - 2, -1, -1):
    s = 0
    for j in range(i + 1, R):
        s += x[j] * M[i][j]
    x[i] = (M[i][C - 1] - s) / M[i][i]

print(x)

[-1.888888888888888, 0.9999999999999994, 3.3703703703703685, -1.0740740740740733]


In [12]:
for i in range(len(x)):
    print(f"x_{i}: {x[i]}")

x_0: -1.888888888888888
x_1: 0.9999999999999994
x_2: 3.3703703703703685
x_3: -1.0740740740740733


## Q2. LU factorization

In [13]:
from scipy import linalg

In [14]:
A = np.array([[2, -1, 2], [2, -3, 3], [6, -1, 8]]).astype("float64")
b = np.array([[-2, -5, 0]]).astype("float64")
print(A.shape)
print(b.shape)

(3, 3)
(1, 3)


In [15]:
b = np.reshape(b, (-1, 1))
b.shape


(3, 1)

In [16]:
P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 0.25       1.        ]]
[[ 6.         -1.          8.        ]
 [ 0.         -2.66666667  0.33333333]
 [ 0.          0.         -0.75      ]]


In [17]:
y = np.linalg.solve(L, np.matmul(P.T, b))
y = np.reshape(y, (3,))
y

array([ 0.  , -5.  , -0.75])

In [18]:
x = np.linalg.solve(U, y)
x

array([-1.,  2.,  1.])

In [19]:
for i in range(len(x)):
    print(f"x_{i}: {x[i]}")

x_0: -0.9999999999999999
x_1: 2.0
x_2: 0.9999999999999999


## Q3. Cholesky factorization

In [20]:
import math

In [21]:
A = np.array([[16, 4, 4], [4, 26, 6], [4, 6, 11]]).astype("float64")
A.shape

(3, 3)

In [22]:
R, C = A.shape
U = np.zeros(A.shape, dtype="float64")

In [23]:
for i in range(R):
    tmp = 0
    for k in range(0, i):
        tmp += U[k][i]**2
    U[i][i] = math.sqrt(A[i][i] - tmp)
    for j in range(i + 1, R):
        tmp = 0
        for k in range(0, i):
            tmp += U[k][i] * U[k][j]
        U[i][j] = (A[i][j] - tmp) / U[i][i]


In [24]:
print(U)
print(U.T)

[[4. 1. 1.]
 [0. 5. 1.]
 [0. 0. 3.]]
[[4. 0. 0.]
 [1. 5. 0.]
 [1. 1. 3.]]


In [25]:
print(A)
print(np.matmul(U.T, U))

[[16.  4.  4.]
 [ 4. 26.  6.]
 [ 4.  6. 11.]]
[[16.  4.  4.]
 [ 4. 26.  6.]
 [ 4.  6. 11.]]
